try:
    from escpos.printer import Usb
    printer = Usb(0xfe6, 0x811e)
except:
    print("no printer")


def printTicket(bznsName, bznsAdd, vehType, vehNo, inTime, inDate, qrData, parkingChargesData, lostTicketCharge, gstNo,ticketNo):
    try:
        printer.control("LF")
        printer.set(font='a', height=1, width=2, align='center')
        printer.text(bznsName)
        printer.set(font='a', height=1, width=1, align='center')
        printer.text("\n")
        printer.text(bznsAdd)
        printer.text("\nVeh Type : ")
        printer.set(font='a', height=1, width=2, align='center')
        printer.text(vehType)
        printer.set(font='a', height=1, width=1, align='center')
        printer.text("\nVeh No : ")
        printer.set(font='a', height=1, width=2, align='center')
        # printer.text(vehNo)
        printer.text("\n")
        printer.image(vehNo)
        printer.text("\nIN:")
        printer.text(inTime)
        printer.set(font='a', height=1, width=1, align='center')
        printer.text(" DT :")
        printer.text(inDate)
        printer.text("\n")
        printer.qr(qrData, size=7, native=True)
        printer.text(parkingChargesData)
        #printer.set(font='a', height=1, width=1, align='center', text_type='U')
        #printer.text("\nLost Ticket Charge :")
        #printer.text(lostTicketCharge)
        #printer.set(font='a', height=1, width=1,align='center', text_type='NORMAL')
        #printer.text("\nInclusive of GST, GST No:")
        #printer.text("\n")
        #printer.text(gstNo)
        printer.text("\nParking at Owner's risk.")
        printer.text("\nPowered by GetParking")
        printer.text("\nT&C applicable .")
        printer.text("\nENTRY TICKET:")
        printer.set(font='a', height=1, width=2, align='center')
        printer.text(ticketNo)
        printer.set(font='a', height=1, width=1, align='center')
        printer.cut("FULL")
    except:
        pass


def printReceipt(bznsName, bznsAdd, vehType, vehNo, inTime, inDate, outTime, outDate, dur, entryAmt, exitamt, gstNo,
                 attendant, receiptNo):
    printer.control("LF")
    printer.set(font='a', height=1, width=2, align='center')
    printer.text(bznsName)
    printer.set(font='a', height=1, width=1, align='center')
    printer.text("\n")
    printer.text(bznsAdd)
    printer.text("\nVeh Type :")
    printer.text(vehType)
    printer.text(" Veh No :")
    printer.text(vehNo)
    printer.text("\nIN : ")
    printer.text(inTime)
    printer.text(" DT : ")
    printer.text(inDate)
    printer.text("\nOUT : ")
    printer.text(outTime)
    printer.text(" DT : ")
    printer.text(outDate)
    printer.text("\nParking Dur : ")
    printer.set(font='a', height=1, width=2, align='center')
    printer.text(dur)
    printer.set(font='a', height=1, width=1, align='center')
    printer.text("\nEXIT AMT:")
    printer.set(font='a', height=1, width=2, align='center')
    printer.text(exitamt)
    printer.set(font='a', height=1, width=1, align='center')
    printer.text(" ENTRY AMT:")
    printer.text(entryAmt)
    printer.text("\nInclusive of GST, GST No :")
    printer.text("\n")
    printer.text(gstNo)
    printer.text("\nParking at Owner's risk.")
    printer.text("\nPowered by GetParking")
    printer.text("\nT&C applicable .")
    printer.text("\nATTENDANT-")
    printer.text(attendant)
    printer.text("\nEXIT RECEIPT :")
    printer.set(font='a', height=1, width=2, align='center')
    printer.text(receiptNo)
    printer.set(font='a', height=1, width=1, align='center')
    printer.cut("FULL")


if __name__ == '__main__':
    printTicket("BIG CENTRE","Ghodbunder Road, Thane West","2W","1234","12:00","16/05/19","04061914:05123452323","Prking Charges :\nUp to 10min:Rs.00,\nUpto 4Hr:Rs.10, 8Hr:Rs.30,\n24Hr:Rs.50,","100","27AAHCP8201E1ZL","T13213")
    #printReceipt("BIG CENTRE","Ghodbunder Road, Thane West","2W","1234","12:00","16/05/19","03:00","16/05/19","03:00","60","00","27AAHCP8201E1ZL","R020201")
